<?php
/**
 * Test class for global functions
 * Generated by PHPUnit on 2007-10-22 at 13:24:06.
 */
class gvhGlobalTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * comprobar si existe la variable necesaria para aplicacion
     */
    public function testExisteVarAplicacion() {
    	//TODO: esta comprobacion seguramente ira en clase ConfigFrameworkTest
        $conf = ConfigFramework::getConfig()->getApplicationName();
        $this->assertTrue(!empty($conf),"No definida variable 'aplicacion'");
		$this->assertInternalType('string', $conf);    	
    }

    /**
     * comprobar si existe la variable casi-necesaria para aplicacion
     */
    public function testExisteVersion() {
    	//TODO: esta comprobacion seguramente ira en clase ConfigFrameworkTest
        $conf = ConfigFramework::getConfig()->getAppVersion();
        $this->assertTrue(!empty($conf),"No definida variable 'verion'");
		$this->assertInternalType('string', $conf);    	
    }

    /**
     * comprobar si existe la variable necesaria para aplicacion
     */
    public function testExisteVarLog() {
    	$log = ConfigFramework::getConfig()->getLogStatus();
        $this->assertTrue(isset($log),"No definida variable 'log'");
		$this->assertInternalType('integer', $log);    	
    }

    /**
     * comprobar si existe la variable necesaria para aplicacion
     */
    public function testExisteVarTipoConsulta() {
    	$gint_tipoConsulta  = ConfigFramework::getConfig()->getQueryMode();
        $this->assertTrue(!empty($gint_tipoConsulta),"No definida variable 'tipoConsulta'");
		$this->assertInternalType('integer', $gint_tipoConsulta);    	
    }

}

?>
